name: Build and Deploy Nikola to GitHub Pages

on:
  push:
    branches:
      - master  # Changed to master instead of main

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Deploy Nikola to GitHub Pages'
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install Nikola and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev
        sudo pip3 install nikola

    - name: Build and Deploy Nikola with Safe Directory Fix
      run: |
        docker run --rm -v $GITHUB_WORKSPACE:/workspace -e GITHUB_WORKSPACE=$GITHUB_WORKSPACE -e GITHUB_TOKEN=$GITHUB_TOKEN \
        ubuntu:latest bash -c "
          apt-get update && apt-get install -y git && 
          git config --global --add safe.directory /workspace && 
          nikola build && 
          nikola deploy"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
