name: Build and Deploy Nikola to GitHub Pages

on:
  push:
    branches:
      - master  # or the branch you're pushing to

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Deploy Nikola to GitHub Pages'
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Configure Git to treat the directory as safe
      run: git config --global --add safe.directory /github/workspace

    - name: Build and Deploy Nikola
      uses: getnikola/nikola-action@v2
