name: Build and Deploy Nikola to GitHub Pages

on:
  push:
    branches:
      - master  # or the branch you're pushing to

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Deploy Nikola to GitHub Pages'
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build and Deploy Nikola with Safe Directory Fix
      run: |
        docker run --rm -v $GITHUB_WORKSPACE:/workspace -e GITHUB_WORKSPACE=$GITHUB_WORKSPACE -e GITHUB_TOKEN=$GITHUB_TOKEN \
        ubuntu:latest bash -c "git config --global --add safe.directory /workspace && nikola build && nikola deploy"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
